### ISSUE TITLE
能不能加一个自动解锁的功能?

### ISSUE THREAD

**Issue by linsan970809** [tumuyan/AnyLauncher#13]
手写感谢大神开发了这个工具,
让我把手机当车机的并启动自己程序的想法得到了实现,
但是我这个手机是魅族的就算把密码和不锁屏都设置了,系统启动的时候还是要上滑一次来解锁(后面就不用了)
不知道大神能不能加一个小功能让系统启动后自动就解锁了
资料我都查好了
https://blog.csdn.net/zhonglunshun/article/details/78112803
可惜我不会弄,十分感谢

**Comment by tumuyan** [comment]
[Anylauncher-1.13.apk.zip](https://github.com/tumuyan/AnyLauncher/files/15047970/Anylauncher-1.13.apk.zip)

请你确认一下不设置锁屏的前提下，是不是能够开机直接进入应用。

**Comment by linsan970809** [comment]
> [Anylauncher-1.13.apk.zip](https://github.com/tumuyan/AnyLauncher/files/15047970/Anylauncher-1.13.apk.zip)
> 
> 请你确认一下不设置锁屏的前提下，是不是能够开机直接进入应用。

我原来的流程是,anyl作为启动桌面->它带起我要的程序
晚上收到你的程序以后,我把我的程序换成了QQ音乐设置了启动自动播放,测试是通过的.
我开机后,没有上滑解锁,QQ音乐正常启动并且在未解锁状态下开始播放音乐了,但是手机并没有解锁到桌面,也就是说它是在锁屏界面播放的音乐.
可能我这个设想其实是走不通的,谢谢你了

**Comment by tumuyan** [comment]
> 我开机后,没有上滑解锁,QQ音乐正常启动并且在未解锁状态下开始播放音乐了,但是手机并没有解锁到桌面,也就是说它是在锁屏界面播放的音乐.

从你的描述看基本是符合预期的。你给的参考文章其实说明的很清楚了，开机进入应用包含了两部分的功能：
1. 开机后不需解锁就进入这个应用
2. 即使锁屏仍然在锁屏的上层显示这个应用

但是按说播放器本身应该是有第二点的功能的，即锁屏也能显示大封面和播放控件，所以大致能用的状态？

**Comment by linsan970809** [comment]
对,播放器有一个大封面在锁屏上显示,只要上滑这个播放界面也能解锁进桌面,并不需要解锁两次,感觉是QQ音乐接管了这个锁屏界面

**Comment by linsan970809** [comment]
> > 我开机后,没有上滑解锁,QQ音乐正常启动并且在未解锁状态下开始播放音乐了,但是手机并没有解锁到桌面,也就是说它是在锁屏界面播放的音乐.
> 
> 从你的描述看基本是符合预期的。你给的参考文章其实说明的很清楚了，开机进入应用包含了两部分的功能：
> 
> 1. 开机后不需解锁就进入这个应用
> 2. 即使锁屏仍然在锁屏的上层显示这个应用
> 
> 但是按说播放器本身应该是有第二点的功能的，即锁屏也能显示大封面和播放控件，所以大致能用的状态？

对,播放器有一个大封面在锁屏上显示,只要上滑这个播放界面也能解锁进桌面,并不需要解锁两次,感觉是QQ音乐接管了这个锁屏界面

**Comment by tumuyan** [comment]
OK
 那你认为需要保留这个功能吗？还是事实上用不到

**Comment by linsan970809** [comment]
我不太清楚需求这个功能的人多不多,不过我测试了两个设备都没有生效.那我个人觉得就没有保留的必要了
谢谢你了

**Comment by tumuyan** [comment]
好的
