### ISSUE TITLE
索尼55x85k电视无法选择应用

### ISSUE THREAD

**Issue by Shimmer2** [tumuyan/AnyLauncher#7]
索尼55x85k电视无法选择应用，安卓10系统的，选择应用后按确认没有任何反应

**Comment by Shimmer2** [comment]
遥控器选择不了应用，后来插上鼠标就可以选择了，希望下次更新能优化一下遥控器操作！这个软件太棒了！解决了我开机直达直播的问题！

**Comment by tumuyan** [comment]
现在应该可以了

**Comment by Shimmer2** [comment]
请问有没有办法做到：开机后自动打开指定app，然后按home按键回到默认的桌面，我想实现电视开机后直接打开iptv软件播放指定的频道，home键正常返回自带桌面

**Comment by tumuyan** [comment]
你需要找一个自动化脚本的软件，添加开机启动xxApp的任务。
