### ISSUE TITLE
小米电视4A 设置桌面闪退

### ISSUE THREAD

**Issue by towerbit** [tumuyan/AnyLauncher#8]
安卓6.0，MIUI TV版本 1.3.125(稳定版) 

点击“设置桌面”按钮后，软件直接无提示闪退了

**Comment by towerbit** [comment]
点击选择应用—备用启动器，可以看到
-------------------------
桌面(.MainActivityUserMode) com.mitv.tvhome
当贝桌面 
AnyLancher(.MainActivity)
-------------------------
也可以选择并返回

**Comment by tumuyan** [comment]
这个按钮不能保障100%有效，我也没有任何机器可以调试和验证。
建议选择好参数后，在系统的设置界面中选择并完成设置。

**Comment by towerbit** [comment]
谢谢回复，最终删除系统自带的 tvhome 桌面了事
